services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: tasks_mngr_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: task_management_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: